import AppKit
import Foundation

@MainActor
enum PasteboardReader {
    static let maximumPayloadBytes = 10 * 1_024 * 1_024

    private static let confidentialMarkers = [
        "concealed",
        "confidential",
        "transienttype",
        "autogeneratedtype",
        "com.agilebits.onepassword",
        "org.keepassxc"
    ]

    static func read(
        from pasteboard: NSPasteboard,
        captureImages: Bool,
        captureFiles: Bool
    ) -> ClipboardPayload? {
        let items = pasteboard.pasteboardItems ?? []
        guard !items.isEmpty, !containsConfidentialMarker(items) else { return nil }

        if captureFiles {
            let options: [NSPasteboard.ReadingOptionKey: Any] = [.urlReadingFileURLsOnly: true]
            let fileURLs = (pasteboard.readObjects(forClasses: [NSURL.self], options: options) ?? [])
                .compactMap { object -> URL? in
                    if let url = object as? URL { return url }
                    if let url = object as? NSURL { return url as URL }
                    return nil
            }
                .filter(\.isFileURL)
            if !fileURLs.isEmpty {
                let references = fileURLs.compactMap(ClipboardFileReference.capture)
                guard references.count == fileURLs.count else { return nil }
                let payload = ClipboardPayload.files(references)
                return payload.byteCount <= maximumPayloadBytes ? payload : nil
            }
        }

        if captureImages {
            for item in items {
                for type in [NSPasteboard.PasteboardType.png, .tiff] {
                    guard let data = item.data(forType: type) else { continue }
                    guard data.count <= maximumPayloadBytes, NSImage(data: data) != nil else { continue }
                    return .image(data: data, typeIdentifier: type.rawValue)
                }
            }
        }

        guard let plain = pasteboard.string(forType: .string), !plain.isEmpty else { return nil }
        let firstItem = items.first
        var rtf = firstItem?.data(forType: .rtf)
        var html = firstItem?.data(forType: .html)
        if plain.utf8.count + (rtf?.count ?? 0) + (html?.count ?? 0) > maximumPayloadBytes {
            rtf = nil
            html = nil
        }

        let payload = ClipboardPayload.text(plain: plain, rtf: rtf, html: html)
        return payload.byteCount <= maximumPayloadBytes ? payload : nil
    }

    private static func containsConfidentialMarker(_ items: [NSPasteboardItem]) -> Bool {
        items.flatMap(\.types).contains { type in
            let normalized = type.rawValue.lowercased()
            return confidentialMarkers.contains { normalized.contains($0) }
        }
    }
}
